### ISSUE TITLE
Frontend minor bug fixes

### ISSUE THREAD

**Issue by BlackStar5044** [sopra-fs22-group-13/braendi-dog-client#58]
- [x] - Password hidden
- [x] - 4/4 displays as 'start' for owner
- [x] - Take out PawIcons
- [x] - alert components
- [x] - Rules get displayed differently in game
- [ ] - Restructuring of boardData/ boardUpdate
- [x] - Sidebar: remove hover/ highlight effect of active button

**Comment by LucaZwahlen** [comment]
2591e22bc3c6bf0357474b6846914263ef78aa0b
